//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPro.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account Information 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address1 的本地化字符串。
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address2 的本地化字符串。
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address3 的本地化字符串。
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address4 的本地化字符串。
        /// </summary>
        public static string Address4 {
            get {
                return ResourceManager.GetString("Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addresses 的本地化字符串。
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AliaseName 的本地化字符串。
        /// </summary>
        public static string AliaseName {
            get {
                return ResourceManager.GetString("AliaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaseInfo 的本地化字符串。
        /// </summary>
        public static string BaseInfo {
            get {
                return ResourceManager.GetString("BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Desc 的本地化字符串。
        /// </summary>
        public static string ClntDesc {
            get {
                return ResourceManager.GetString("ClntDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client IDN 的本地化字符串。
        /// </summary>
        public static string ClntIDN {
            get {
                return ResourceManager.GetString("ClntIDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Type 的本地化字符串。
        /// </summary>
        public static string ClntType {
            get {
                return ResourceManager.GetString("ClntType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communications 的本地化字符串。
        /// </summary>
        public static string Communications {
            get {
                return ResourceManager.GetString("Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CompCode 的本地化字符串。
        /// </summary>
        public static string CompCode {
            get {
                return ResourceManager.GetString("CompCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfirmPass 的本地化字符串。
        /// </summary>
        public static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date1 的本地化字符串。
        /// </summary>
        public static string Date1 {
            get {
                return ResourceManager.GetString("Date1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date2 的本地化字符串。
        /// </summary>
        public static string Date2 {
            get {
                return ResourceManager.GetString("Date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date3 的本地化字符串。
        /// </summary>
        public static string Date3 {
            get {
                return ResourceManager.GetString("Date3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FullName 的本地化字符串。
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Street 的本地化字符串。
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Street1 的本地化字符串。
        /// </summary>
        public static string Street1 {
            get {
                return ResourceManager.GetString("Street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USrName 的本地化字符串。
        /// </summary>
        public static string USrName {
            get {
                return ResourceManager.GetString("USrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UsrPass 的本地化字符串。
        /// </summary>
        public static string UsrPass {
            get {
                return ResourceManager.GetString("UsrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZipCode 的本地化字符串。
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
