//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETPro.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account Information 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActivatDate 的本地化字符串。
        /// </summary>
        public static string ActivatDate {
            get {
                return ResourceManager.GetString("ActivatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 פעיל 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address1 的本地化字符串。
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address2 的本地化字符串。
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address3 的本地化字符串。
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address4 的本地化字符串。
        /// </summary>
        public static string Address4 {
            get {
                return ResourceManager.GetString("Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addresses 的本地化字符串。
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdminDate 的本地化字符串。
        /// </summary>
        public static string AdminDate {
            get {
                return ResourceManager.GetString("AdminDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdminDate1 的本地化字符串。
        /// </summary>
        public static string AdminDate1 {
            get {
                return ResourceManager.GetString("AdminDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdminDate2 的本地化字符串。
        /// </summary>
        public static string AdminDate2 {
            get {
                return ResourceManager.GetString("AdminDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdminDate3 的本地化字符串。
        /// </summary>
        public static string AdminDate3 {
            get {
                return ResourceManager.GetString("AdminDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdminDate4 的本地化字符串。
        /// </summary>
        public static string AdminDate4 {
            get {
                return ResourceManager.GetString("AdminDate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AliaseName 的本地化字符串。
        /// </summary>
        public static string AliaseName {
            get {
                return ResourceManager.GetString("AliaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AriveHour 的本地化字符串。
        /// </summary>
        public static string AriveHour {
            get {
                return ResourceManager.GetString("AriveHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaseInfo 的本地化字符串。
        /// </summary>
        public static string BaseInfo {
            get {
                return ResourceManager.GetString("BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BrakesDate 的本地化字符串。
        /// </summary>
        public static string BrakesDate {
            get {
                return ResourceManager.GetString("BrakesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClientName 的本地化字符串。
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClntAddishtionCharge 的本地化字符串。
        /// </summary>
        public static string ClntAddishtionCharge {
            get {
                return ResourceManager.GetString("ClntAddishtionCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClntAddishtionCredit 的本地化字符串。
        /// </summary>
        public static string ClntAddishtionCredit {
            get {
                return ResourceManager.GetString("ClntAddishtionCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Desc 的本地化字符串。
        /// </summary>
        public static string ClntDesc {
            get {
                return ResourceManager.GetString("ClntDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client IDN 的本地化字符串。
        /// </summary>
        public static string ClntIDN {
            get {
                return ResourceManager.GetString("ClntIDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Type 的本地化字符串。
        /// </summary>
        public static string ClntType {
            get {
                return ResourceManager.GetString("ClntType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommitionFee 的本地化字符串。
        /// </summary>
        public static string CommitionFee {
            get {
                return ResourceManager.GetString("CommitionFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommitionToId 的本地化字符串。
        /// </summary>
        public static string CommitionToId {
            get {
                return ResourceManager.GetString("CommitionToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communications 的本地化字符串。
        /// </summary>
        public static string Communications {
            get {
                return ResourceManager.GetString("Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommuType 的本地化字符串。
        /// </summary>
        public static string CommuType {
            get {
                return ResourceManager.GetString("CommuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommuValue 的本地化字符串。
        /// </summary>
        public static string CommuValue {
            get {
                return ResourceManager.GetString("CommuValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CompCode 的本地化字符串。
        /// </summary>
        public static string CompCode {
            get {
                return ResourceManager.GetString("CompCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfirmPass 的本地化字符串。
        /// </summary>
        public static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentKM 的本地化字符串。
        /// </summary>
        public static string CurrentKM {
            get {
                return ResourceManager.GetString("CurrentKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date1 的本地化字符串。
        /// </summary>
        public static string Date1 {
            get {
                return ResourceManager.GetString("Date1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date2 的本地化字符串。
        /// </summary>
        public static string Date2 {
            get {
                return ResourceManager.GetString("Date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date3 的本地化字符串。
        /// </summary>
        public static string Date3 {
            get {
                return ResourceManager.GetString("Date3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desc 的本地化字符串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DistanceKM 的本地化字符串。
        /// </summary>
        public static string DistanceKM {
            get {
                return ResourceManager.GetString("DistanceKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DocCtg 的本地化字符串。
        /// </summary>
        public static string DocCtg {
            get {
                return ResourceManager.GetString("DocCtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DocName 的本地化字符串。
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DocPath 的本地化字符串。
        /// </summary>
        public static string DocPath {
            get {
                return ResourceManager.GetString("DocPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DocText 的本地化字符串。
        /// </summary>
        public static string DocText {
            get {
                return ResourceManager.GetString("DocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DrvAddishtionCharge 的本地化字符串。
        /// </summary>
        public static string DrvAddishtionCharge {
            get {
                return ResourceManager.GetString("DrvAddishtionCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DrvAddishtionCredit 的本地化字符串。
        /// </summary>
        public static string DrvAddishtionCredit {
            get {
                return ResourceManager.GetString("DrvAddishtionCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DrvDesc 的本地化字符串。
        /// </summary>
        public static string DrvDesc {
            get {
                return ResourceManager.GetString("DrvDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DrvFee 的本地化字符串。
        /// </summary>
        public static string DrvFee {
            get {
                return ResourceManager.GetString("DrvFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DryShtlsPassenger 的本地化字符串。
        /// </summary>
        public static string DryShtlsPassenger {
            get {
                return ResourceManager.GetString("DryShtlsPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DryText 的本地化字符串。
        /// </summary>
        public static string DryText {
            get {
                return ResourceManager.GetString("DryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EvntDate_YYYYMMDD 的本地化字符串。
        /// </summary>
        public static string EvntDate_YYYYMMDD {
            get {
                return ResourceManager.GetString("EvntDate_YYYYMMDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EvntText 的本地化字符串。
        /// </summary>
        public static string EvntText {
            get {
                return ResourceManager.GetString("EvntText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeAtHour 的本地化字符串。
        /// </summary>
        public static string FreeAtHour {
            get {
                return ResourceManager.GetString("FreeAtHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequence 的本地化字符串。
        /// </summary>
        public static string Frequence {
            get {
                return ResourceManager.GetString("Frequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friday 的本地化字符串。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FromLocation 的本地化字符串。
        /// </summary>
        public static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FullName 的本地化字符串。
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HasWIFI 的本地化字符串。
        /// </summary>
        public static string HasWIFI {
            get {
                return ResourceManager.GetString("HasWIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 לא פעיל 的本地化字符串。
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsApproved 的本地化字符串。
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsChecked 的本地化字符串。
        /// </summary>
        public static string IsChecked {
            get {
                return ResourceManager.GetString("IsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsDoneOk 的本地化字符串。
        /// </summary>
        public static string IsDoneOk {
            get {
                return ResourceManager.GetString("IsDoneOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsFeeChecked 的本地化字符串。
        /// </summary>
        public static string IsFeeChecked {
            get {
                return ResourceManager.GetString("IsFeeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsFinished 的本地化字符串。
        /// </summary>
        public static string IsFinished {
            get {
                return ResourceManager.GetString("IsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsMarkedOk 的本地化字符串。
        /// </summary>
        public static string IsMarkedOk {
            get {
                return ResourceManager.GetString("IsMarkedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsPayed 的本地化字符串。
        /// </summary>
        public static string IsPayed {
            get {
                return ResourceManager.GetString("IsPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReadOnly 的本地化字符串。
        /// </summary>
        public static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsRecorsive 的本地化字符串。
        /// </summary>
        public static string IsRecorsive {
            get {
                return ResourceManager.GetString("IsRecorsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReminder 的本地化字符串。
        /// </summary>
        public static string IsReminder {
            get {
                return ResourceManager.GetString("IsReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LenghtMinutes 的本地化字符串。
        /// </summary>
        public static string LenghtMinutes {
            get {
                return ResourceManager.GetString("LenghtMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linc 的本地化字符串。
        /// </summary>
        public static string Linc {
            get {
                return ResourceManager.GetString("Linc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LncName 的本地化字符串。
        /// </summary>
        public static string LncName {
            get {
                return ResourceManager.GetString("LncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LncText 的本地化字符串。
        /// </summary>
        public static string LncText {
            get {
                return ResourceManager.GetString("LncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LockCode 的本地化字符串。
        /// </summary>
        public static string LockCode {
            get {
                return ResourceManager.GetString("LockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainCateg 的本地化字符串。
        /// </summary>
        public static string MainCateg {
            get {
                return ResourceManager.GetString("MainCateg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufYear 的本地化字符串。
        /// </summary>
        public static string ManufYear {
            get {
                return ResourceManager.GetString("ManufYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monday 的本地化字符串。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NetProfit 的本地化字符串。
        /// </summary>
        public static string NetProfit {
            get {
                return ResourceManager.GetString("NetProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumPsngrs 的本地化字符串。
        /// </summary>
        public static string NumPsngrs {
            get {
                return ResourceManager.GetString("NumPsngrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtInsuranceAt 的本地化字符串。
        /// </summary>
        public static string NxtInsuranceAt {
            get {
                return ResourceManager.GetString("NxtInsuranceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtTestAt 的本地化字符串。
        /// </summary>
        public static string NxtTestAt {
            get {
                return ResourceManager.GetString("NxtTestAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtTimingAt 的本地化字符串。
        /// </summary>
        public static string NxtTimingAt {
            get {
                return ResourceManager.GetString("NxtTimingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtTreatmnt1At 的本地化字符串。
        /// </summary>
        public static string NxtTreatmnt1At {
            get {
                return ResourceManager.GetString("NxtTreatmnt1At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtTreatmnt2At 的本地化字符串。
        /// </summary>
        public static string NxtTreatmnt2At {
            get {
                return ResourceManager.GetString("NxtTreatmnt2At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtTreatmnt3At 的本地化字符串。
        /// </summary>
        public static string NxtTreatmnt3At {
            get {
                return ResourceManager.GetString("NxtTreatmnt3At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NxtTreatmntAt 的本地化字符串。
        /// </summary>
        public static string NxtTreatmntAt {
            get {
                return ResourceManager.GetString("NxtTreatmntAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ObjType 的本地化字符串。
        /// </summary>
        public static string ObjType {
            get {
                return ResourceManager.GetString("ObjType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdDays 的本地化字符串。
        /// </summary>
        public static string OrdDays {
            get {
                return ResourceManager.GetString("OrdDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdDays1111111 的本地化字符串。
        /// </summary>
        public static string OrdDays1111111 {
            get {
                return ResourceManager.GetString("OrdDays1111111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdIfExtraHours 的本地化字符串。
        /// </summary>
        public static string OrdIfExtraHours {
            get {
                return ResourceManager.GetString("OrdIfExtraHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdIsActive 的本地化字符串。
        /// </summary>
        public static string OrdIsActive {
            get {
                return ResourceManager.GetString("OrdIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdNum 的本地化字符串。
        /// </summary>
        public static string OrdNum {
            get {
                return ResourceManager.GetString("OrdNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdPath 的本地化字符串。
        /// </summary>
        public static string OrdPath {
            get {
                return ResourceManager.GetString("OrdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdTime 的本地化字符串。
        /// </summary>
        public static string OrdTime {
            get {
                return ResourceManager.GetString("OrdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrdType 的本地化字符串。
        /// </summary>
        public static string OrdType {
            get {
                return ResourceManager.GetString("OrdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OthrCosts 的本地化字符串。
        /// </summary>
        public static string OthrCosts {
            get {
                return ResourceManager.GetString("OthrCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PerHour 的本地化字符串。
        /// </summary>
        public static string PerHour {
            get {
                return ResourceManager.GetString("PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PersonName 的本地化字符串。
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PersonRole 的本地化字符串。
        /// </summary>
        public static string PersonRole {
            get {
                return ResourceManager.GetString("PersonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PerWaitHour 的本地化字符串。
        /// </summary>
        public static string PerWaitHour {
            get {
                return ResourceManager.GetString("PerWaitHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone1 的本地化字符串。
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone2 的本地化字符串。
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone3 的本地化字符串。
        /// </summary>
        public static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopUpAt_YYYYMMDDHHMM 的本地化字符串。
        /// </summary>
        public static string PopUpAt_YYYYMMDDHHMM {
            get {
                return ResourceManager.GetString("PopUpAt_YYYYMMDDHHMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiver 的本地化字符串。
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecorsivType 的本地化字符串。
        /// </summary>
        public static string RecorsivType {
            get {
                return ResourceManager.GetString("RecorsivType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemText 的本地化字符串。
        /// </summary>
        public static string RemText {
            get {
                return ResourceManager.GetString("RemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saturday 的本地化字符串。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScndCateg 的本地化字符串。
        /// </summary>
        public static string ScndCateg {
            get {
                return ResourceManager.GetString("ScndCateg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sender 的本地化字符串。
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShtlDateYYYYMMDD 的本地化字符串。
        /// </summary>
        public static string ShtlDateYYYYMMDD {
            get {
                return ResourceManager.GetString("ShtlDateYYYYMMDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShtlDay 的本地化字符串。
        /// </summary>
        public static string ShtlDay {
            get {
                return ResourceManager.GetString("ShtlDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShtlMonth 的本地化字符串。
        /// </summary>
        public static string ShtlMonth {
            get {
                return ResourceManager.GetString("ShtlMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShtlYear 的本地化字符串。
        /// </summary>
        public static string ShtlYear {
            get {
                return ResourceManager.GetString("ShtlYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartHour 的本地化字符串。
        /// </summary>
        public static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Street 的本地化字符串。
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Street1 的本地化字符串。
        /// </summary>
        public static string Street1 {
            get {
                return ResourceManager.GetString("Street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThrdCateg 的本地化字符串。
        /// </summary>
        public static string ThrdCateg {
            get {
                return ResourceManager.GetString("ThrdCateg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thursday 的本地化字符串。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TName 的本地化字符串。
        /// </summary>
        public static string TName {
            get {
                return ResourceManager.GetString("TName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToLocation 的本地化字符串。
        /// </summary>
        public static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TotalCost 的本地化字符串。
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TotWaitMinutes 的本地化字符串。
        /// </summary>
        public static string TotWaitMinutes {
            get {
                return ResourceManager.GetString("TotWaitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuesday 的本地化字符串。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TValue 的本地化字符串。
        /// </summary>
        public static string TValue {
            get {
                return ResourceManager.GetString("TValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USrName 的本地化字符串。
        /// </summary>
        public static string USrName {
            get {
                return ResourceManager.GetString("USrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UsrPass 的本地化字符串。
        /// </summary>
        public static string UsrPass {
            get {
                return ResourceManager.GetString("UsrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VehCode 的本地化字符串。
        /// </summary>
        public static string VehCode {
            get {
                return ResourceManager.GetString("VehCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VehFee 的本地化字符串。
        /// </summary>
        public static string VehFee {
            get {
                return ResourceManager.GetString("VehFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VehType 的本地化字符串。
        /// </summary>
        public static string VehType {
            get {
                return ResourceManager.GetString("VehType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekDay 的本地化字符串。
        /// </summary>
        public static string WeekDay {
            get {
                return ResourceManager.GetString("WeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinterDate 的本地化字符串。
        /// </summary>
        public static string WinterDate {
            get {
                return ResourceManager.GetString("WinterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worthy 的本地化字符串。
        /// </summary>
        public static string Worthy {
            get {
                return ResourceManager.GetString("Worthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZipCode 的本地化字符串。
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
